server:
  port: 8082
spring:
  application:
    name: flash-card-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dict

springdoc:
  swagger-ui:
    path: /swagger-ui.html

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.13